services:
  traefik:
    image: traefik:latest
    # ports:
    #   - 80:80
    #   - 443:443
    restart: always
    network_mode: host
    
    volumes:
      - traefik-public-certificates:/certificates
      - dynamic-config:/etc/traefik/dynamic

    command:
      - --providers.file.directory=/etc/traefik/dynamic # Specify directory for dynamic configuration
      - --providers.http  # Enable HTTP provider
      - --providers.http.endpoint=http://128.199.30.61:3000/api/traefik
      - --api.insecure=true
      - --entrypoints.http.address=:8081
      - --entrypoints.https.address=:443 # https
      - --certificatesresolvers.myresolver.acme.email=imbhaskaran@gmail.com # https
      - --certificatesresolvers.myresolver.acme.storage=/certificates/acme.json #ssl certificate storage
      - --certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=http


      - --accesslog
      - --log
      - --api
    # networks:
      # - cloudbox
volumes:
  traefik-public-certificates:
  dynamic-config:

networks:
  cloudbox:
    external: true
