services:
  cloudbox-web:

  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      ## configure http
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.ibhaskar.com`)
      ## configure https
      - traefik.http.routers.traefik-dashboard-https.entrypoints=https
      - traefik.http.routers.traefik-dashboard-https.tls.certresolver=myresolver
      - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.ibhaskar.com`)
      - traefik.http.routers.traefik-dashboard-https.service=api@internal
      - traefik.http.routers.traefik-dashboard-https.tls=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

    volumes:
      - traefik-public-certificates:/certificates
      - dynamic-config:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic # Specify directory for dynamic configuration
      - --providers.http # Enable HTTP provider
      - --providers.http.endpoint=http://128.199.30.61:3000/api/traefik
      - --api.insecure=true
      - --providers.http.PollInterval=5
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443 # https

      - --certificatesresolvers.myresolver.acme.email=imbhaskaran@gmail.com # https
      - --certificatesresolvers.myresolver.acme.storage=/certificates/acme.json #ssl certificate storage
      - --certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=http
      - --accesslog
      - --log.level=DEBUG
      - --api
    networks:
      - cloudbox
volumes:
  traefik-public-certificates:
  dynamic-config:

networks:
  cloudbox:
    external: true
